### ISSUE TITLE
Let's find a proper name

### ISSUE THREAD

**Issue by kennethlarsen** [kennethlarsen/thecatgame#3]
Let's use this issue for keeping track of possible names:

- Mewment

- Cat-titude

- Claw-some

**Comment by paulgoetze** [comment]
* Purrturbation 
  (from perturbation: A small distortion (from its normal shape) of an object or of the spacetime curvature around an object, found [here](http://www.andersoninstitute.com/time-travel-terms-and-definitions.html))
* Quantikittics 
  (from Quantikistics – Term invented by US chrononaut Andrew D. Basiago to describe the effects of time travel on ~human~ *cat* society, found [here](https://timelyparadox.com/2016/12/18-time-travel-terms-defined-by-andy-basiago-self-proclaimed-time-traveler))

**Comment by paulgoetze** [comment]
And the winner is: *PURRTURBATION* 🎉
